-- 코드를 입력하세요
# SELECT floor(price) as PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS
# FROM PRODUCT
# GROUP BY floor(price) 
# ORDER BY floor(price) ASC;

SELECT CAST(CONCAT(SUBSTRING(PRICE, 1, 1),'0000') AS UNSIGNED) AS PRICE_GROUP, COUNT(product_code) AS PRODUCTS
FROM PRODUCT
GROUP BY CONCAT(SUBSTRING(PRICE, 1, 1),'0000')
ORDER BY CONCAT(SUBSTRING(PRICE, 1, 1),'0000');