-- 코드를 입력하세요
SELECT k.APNT_NO, k.PT_NAME, k.PT_NO, k.MCDP_CD, d.DR_NAME, k.APNT_YMD
FROM DOCTOR d RIGHT JOIN 
    (SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, a.APNT_YMD, a.MDDR_ID
    FROM APPOINTMENT a LEFT JOIN PATIENT p ON a.PT_NO = p.PT_NO 
    WHERE APNT_CNCL_YN = 'N' AND APNT_YMD LIKE "2022-04-13%") k 
ON d.DR_ID = k.MDDR_ID
ORDER BY k.APNT_YMD ASC;

