-- 코드를 입력하세요

SELECT p.MEMBER_NAME, r.REVIEW_TEXT, r.REVIEW_DATE
FROM MEMBER_PROFILE p JOIN REST_REVIEW r ON p.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID = (SELECT MEMBER_ID 
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1)
ORDER BY r.REVIEW_DATE,r.REVIEW_TEXT ;