# -- 코드를 작성해주세요
# SELECT ID, GENOTYPE, PARENT_ID AS PARENT_GENOTYPE
# FROM ECOLI_DATA
# WHERE ID = 2 OR ID = 3 OR ID = 7 OR ID = 8
# ORDER BY ID ASC;

SELECT 
    c.ID,
    c.GENOTYPE,
    p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA c
JOIN ECOLI_DATA p
    ON c.PARENT_ID = p.ID
WHERE (c.GENOTYPE & p.GENOTYPE) = p.GENOTYPE
ORDER BY c.ID;
