-- 코드를 입력하세요
# SELECT USER_ID, PRODUCT_ID
# FROM O.ONLINE_SALE JOIN F.ONLINE_SALE ON ONLINE_SALE_ID
# WHERE (O.USER_ID = F.USER_ID) 
# AND (O.PRODUCT_ID = F.PRODUCT_ID) 
# AND (O.SALES_DATE = F.SALES_DATE) ;


SELECT USER_ID, PRODUCT_ID #, COUNT(*)
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC;